# Generated by Django 5.1.4 on 2026-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_asset_fk_and_user_holding'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetquotesnapshot',
            new_name='idx_quote_asset_time',
            old_name='idx_aqs_asset_time',
        ),
        migrations.RenameIndex(
            model_name='assetquotesnapshot',
            new_name='idx_quote_time',
            old_name='idx_aqs_time',
        ),
        migrations.AddIndex(
            model_name='assetkline',
            index=models.Index(fields=['asset', 'resolution', 'k_time'], name='idx_kline_asset_res_time_asc'),
        ),
    ]
