# Generated by Django 4.2.7 on 2026-01-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='资产代码')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('STOCK', '股票'), ('FUND', '基金'), ('ETF', 'ETF'), ('BOND', '债券')], max_length=20, verbose_name='资产类型')),
                ('market', models.CharField(blank=True, max_length=20, verbose_name='所属市场')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产标的',
                'verbose_name_plural': '资产标的',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('tags_json', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('PUBLISHED', '已发布'), ('REJECTED', '被驳回'), ('TAKEN_DOWN', '下架')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
                'db_table': 'content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('POST', '帖子'), ('COMMENT', '评论'), ('PORTFOLIO', '组合')], max_length=20, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='目标ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='content.content', verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关联时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.asset', verbose_name='资产')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '内容资产关联',
                'verbose_name_plural': '内容资产关联',
                'db_table': 'content_asset',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='assets',
            field=models.ManyToManyField(through='content.ContentAsset', to='content.asset', verbose_name='关联资产'),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='content',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contents', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('HIDDEN', '屏蔽'), ('DELETED', '删除')], default='NORMAL', max_length=20, verbose_name='状态')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.content', verbose_name='所属内容')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment', verbose_name='父评论')),
                ('reply_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_replies', to=settings.AUTH_USER_MODEL, verbose_name='回复用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='asset_code_eb86ae_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='asset_asset_t_0df6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['target_type', 'target_id'], name='like_target__29db34_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'target_type'], name='like_user_id_e6b11b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'target_type', 'target_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='contentasset',
            unique_together={('content', 'asset')},
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', '-created_at'], name='content_status_a94f37_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author', '-created_at'], name='content_author__25d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-published_at'], name='content_publish_356ced_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content', 'created_at'], name='comment_content_d5ec91_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comment_parent__1e9041_idx'),
        ),
    ]
