# Generated by Django 5.1.4 on 2026-02-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_asset_finnhub_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, help_text='Finnhub 返回的 exchange 字段，用于 symbols 导入筛选', max_length=32, verbose_name='交易所（供应商侧）'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict, help_text='存放官网、行业详情等扩展字段', verbose_name='扩展信息'),
        ),
    ]
