# Generated by Django 5.1.4 on 2026-03-26 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_asset_fk_and_user_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='唯一标识')),
                ('board_type', models.CharField(choices=[('MARKET', '市场讨论区'), ('THEME', '主题专区'), ('COMPANY_RESEARCH', '公司研究专区'), ('QA', '问答求助区')], max_length=32, verbose_name='板块类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='系统预置')),
                ('market', models.CharField(blank=True, choices=[('A_SHARE', 'A股'), ('HK_STOCK', '港股'), ('US_STOCK', '美股'), ('FUTURES', '期货')], max_length=20, verbose_name='市场维度')),
                ('industry_code', models.CharField(blank=True, max_length=32, verbose_name='行业编码')),
                ('stock_code', models.CharField(blank=True, max_length=20, verbose_name='个股代码')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.board', verbose_name='父板块')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
                'db_table': 'board',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关联时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.board', verbose_name='板块')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '内容板块关联',
                'verbose_name_plural': '内容板块关联',
                'db_table': 'content_board',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='boards',
            field=models.ManyToManyField(blank=True, through='content.ContentBoard', to='content.board', verbose_name='关联板块'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['board_type', 'status'], name='idx_board_type_status'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['parent', 'sort_order'], name='idx_board_parent_sort'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['status', 'sort_order'], name='idx_board_status_sort'),
        ),
        migrations.AddIndex(
            model_name='contentboard',
            index=models.Index(fields=['board', 'created_at'], name='idx_content_board_board'),
        ),
        migrations.AlterUniqueTogether(
            name='contentboard',
            unique_together={('content', 'board')},
        ),
    ]
