# Generated by Django 5.1.4 on 2026-03-26 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_seed_default_boards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('NORMAL', '普通帖子'), ('LONGFORM', '长文分析'), ('POLL', '投票调研'), ('LIVE', '实时讨论')], default='NORMAL', max_length=20, verbose_name='内容类型')),
                ('format_type', models.CharField(choices=[('PLAIN', '纯文本'), ('RICH_TEXT', '富文本')], default='PLAIN', max_length=20, verbose_name='格式类型')),
                ('repost_count', models.PositiveIntegerField(default=0, verbose_name='转发数')),
                ('forward_count', models.PositiveIntegerField(default=0, verbose_name='分享数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='content.content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '内容扩展',
                'verbose_name_plural': '内容扩展',
                'db_table': 'content_meta',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='投票问题')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='是否可多选')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否关闭')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='content.content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='选项文本')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='票数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.poll', verbose_name='投票')),
            ],
            options={
                'verbose_name': '投票选项',
                'verbose_name_plural': '投票选项',
                'db_table': 'poll_option',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content_attachments/%Y/%m/', verbose_name='附件文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='审核状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.content', verbose_name='内容')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attachments', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '内容附件',
                'verbose_name_plural': '内容附件',
                'db_table': 'content_attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_attachment_status_time'), models.Index(fields=['uploaded_by', '-created_at'], name='idx_attachment_uploader_time')],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('POST', '帖子'), ('COMMENT', '评论')], max_length=20, verbose_name='来源类型')),
                ('source_id', models.PositiveIntegerField(verbose_name='来源ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_sent', to=settings.AUTH_USER_MODEL, verbose_name='提及者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL, verbose_name='被提及者')),
            ],
            options={
                'verbose_name': '提及记录',
                'verbose_name_plural': '提及记录',
                'db_table': 'mention',
                'indexes': [models.Index(fields=['to_user', '-created_at'], name='idx_mention_to_user_time')],
                'unique_together': {('source_type', 'source_id', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.polloption', verbose_name='选项')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.poll', verbose_name='投票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'db_table': 'poll_vote',
                'indexes': [models.Index(fields=['poll', 'user'], name='idx_poll_vote_poll_user')],
                'unique_together': {('poll', 'option', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='转发语')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='转发时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='content.content', verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '转发',
                'verbose_name_plural': '转发',
                'db_table': 'repost',
                'indexes': [models.Index(fields=['content', '-created_at'], name='idx_repost_content_time')],
                'unique_together': {('user', 'content')},
            },
        ),
    ]
