# Generated by Django 5.1.4 on 2026-03-26 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentmeta_poll_polloption_contentattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_attachments/%Y/%m/', verbose_name='附件文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.comment', verbose_name='评论')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '评论附件',
                'verbose_name_plural': '评论附件',
                'db_table': 'comment_attachment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['uploaded_by', '-created_at'], name='idx_cmtatt_uploader_time')],
            },
        ),
    ]
