# Generated by Django 5.1.4 on 2026-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_commentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='moderation_source',
            field=models.CharField(choices=[('MANUAL', '人工'), ('AUTO', '自动规则'), ('REPORT', '举报触发')], default='MANUAL', max_length=16, verbose_name='审核来源'),
        ),
        migrations.AddField(
            model_name='content',
            name='risk_level',
            field=models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], default='LOW', max_length=16, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='content',
            name='risk_score',
            field=models.PositiveIntegerField(default=0, verbose_name='风险分'),
        ),
    ]
