# Generated by Django 5.1.4 on 2026-04-06 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_moderation_source_content_risk_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddIndex(
            model_name='contentasset',
            index=models.Index(fields=['asset', '-created_at'], name='idx_content_asset_time'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='idx_favorite_user_time'),
        ),
    ]
