# Generated by Django 5.1.4 on 2026-04-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_content_fulltext_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/thumbs/%Y/%m/', verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='thumb',
            field=models.FileField(blank=True, help_text='图片附件生成的小图，供列表等场景使用', null=True, upload_to='content_attachments/thumbs/%Y/%m/', verbose_name='缩略图'),
        ),
    ]
