# Generated by Django 4.2.7 on 2026-01-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示昵称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像链接')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('role', models.CharField(choices=[('USER', '普通用户'), ('MODERATOR', '管理员'), ('ADMIN', '超级管理员')], default='USER', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('MUTED', '禁言'), ('BANNED', '封禁')], default='NORMAL', max_length=20, verbose_name='状态')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='粉丝数')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='关注数')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='员工状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInvestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.IntegerField(choices=[(1, '低风险'), (2, '中风险'), (3, '高风险')], default=2, verbose_name='风险等级')),
                ('horizon', models.IntegerField(choices=[(1, '短期'), (2, '中期'), (3, '长期')], default=2, verbose_name='投资期限')),
                ('focus_market', models.JSONField(blank=True, default=list, verbose_name='关注市场')),
                ('preferred_assets', models.JSONField(blank=True, default=list, verbose_name='偏好资产')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invest_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户投资偏好',
                'verbose_name_plural': '用户投资偏好',
                'db_table': 'user_invest_profile',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关注时间')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'user_follow',
                'unique_together': {('follower', 'followee')},
            },
        ),
    ]
