# Generated by Django 4.2.7 on 2026-03-13 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mute_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='禁言截止时间'),
        ),
        migrations.CreateModel(
            name='UserModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MUTE', '禁言'), ('UNMUTE', '解除禁言'), ('BAN', '封禁'), ('UNBAN', '解除封禁'), ('STATUS_CHANGE', '状态变更')], max_length=32, verbose_name='动作类型')),
                ('reason', models.TextField(blank=True, verbose_name='原因说明')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='被处理用户')),
            ],
            options={
                'verbose_name': '用户治理日志',
                'verbose_name_plural': '用户治理日志',
                'db_table': 'user_moderation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
