# Generated by Django 5.1.4 on 2026-03-25 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mute_until_usermoderationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskQuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True, verbose_name='版本号')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('questions', models.JSONField(default=list, verbose_name='题目JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险问卷模板',
                'verbose_name_plural': '风险问卷模板',
                'db_table': 'risk_questionnaire_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_level',
            field=models.CharField(choices=[('UNVERIFIED', '未认证'), ('BASIC', '基础认证'), ('REAL_NAME', '实名认证'), ('PROFESSIONAL', '专业认证')], default='UNVERIFIED', max_length=20, verbose_name='认证等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='手机号已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_status',
            field=models.CharField(choices=[('NONE', '未提交'), ('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='NONE', max_length=20, verbose_name='专业认证状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name_status',
            field=models.CharField(choices=[('NONE', '未提交'), ('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='NONE', max_length=20, verbose_name='实名认证状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_assessment_status',
            field=models.CharField(choices=[('NONE', '未提交'), ('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='NONE', max_length=20, verbose_name='风险评估状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('R1', '保守型'), ('R2', '稳健型'), ('R3', '平衡型'), ('R4', '积极型'), ('R5', '激进型')], max_length=8, null=True, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='v_badge',
            field=models.BooleanField(default=False, verbose_name='加V标识'),
        ),
        migrations.CreateModel(
            name='UserProfessionalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_doc_url', models.URLField(blank=True, verbose_name='从业资格证明')),
                ('education_doc_url', models.URLField(blank=True, verbose_name='学历证明')),
                ('additional_doc_url', models.URLField(blank=True, verbose_name='附加材料')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=16, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_professional_records', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_verifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '专业认证',
                'verbose_name_plural': '专业认证',
                'db_table': 'user_professional_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRealNameVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('id_card_no_masked', models.CharField(max_length=32, verbose_name='身份证号(脱敏)')),
                ('id_card_hash', models.CharField(max_length=128, verbose_name='身份证号哈希')),
                ('face_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='人脸分数')),
                ('ocr_passed', models.BooleanField(default=False, verbose_name='OCR通过')),
                ('liveness_passed', models.BooleanField(default=False, verbose_name='活体通过')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=16, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_real_name_records', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_name_verifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '实名认证',
                'verbose_name_plural': '实名认证',
                'db_table': 'user_real_name_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskQuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='答案JSON')),
                ('score', models.IntegerField(default=0, verbose_name='总分')),
                ('risk_level', models.CharField(choices=[('R1', '保守型'), ('R2', '稳健型'), ('R3', '平衡型'), ('R4', '积极型'), ('R5', '激进型')], max_length=8, verbose_name='风险等级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_submissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='accounts.riskquestionnairetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '风险问卷提交',
                'verbose_name_plural': '风险问卷提交',
                'db_table': 'risk_questionnaire_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='risk_questi_user_id_4acc42_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WECHAT', '微信'), ('WEIBO', '微博')], max_length=20, verbose_name='平台')),
                ('provider_uid', models.CharField(max_length=128, verbose_name='平台用户ID')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='UnionID')),
                ('openid', models.CharField(blank=True, max_length=128, null=True, verbose_name='OpenID')),
                ('access_token', models.TextField(blank=True, verbose_name='访问令牌')),
                ('refresh_token', models.TextField(blank=True, verbose_name='刷新令牌')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方账号绑定',
                'verbose_name_plural': '第三方账号绑定',
                'db_table': 'user_social_account',
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
        migrations.CreateModel(
            name='UserVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', '邮箱'), ('PHONE', '手机')], max_length=16, verbose_name='渠道')),
                ('target', models.CharField(max_length=255, verbose_name='目标地址')),
                ('purpose', models.CharField(choices=[('REGISTER', '注册'), ('LOGIN', '登录'), ('PASSWORD_RESET', '找回密码'), ('VERIFY_CONTACT', '验证联系方式')], max_length=32, verbose_name='用途')),
                ('code', models.CharField(max_length=16, verbose_name='验证码')),
                ('status', models.CharField(choices=[('SENT', '已发送'), ('VERIFIED', '已验证'), ('EXPIRED', '已过期'), ('INVALID', '已作废')], default='SENT', max_length=16, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'db_table': 'user_verification_code',
                'indexes': [models.Index(fields=['target', 'purpose', 'created_at'], name='user_verifi_target_416ede_idx'), models.Index(fields=['status', 'expires_at'], name='user_verifi_status_8cc711_idx')],
            },
        ),
    ]
