# Generated by Django 5.1.4 on 2026-03-25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_riskquestionnairetemplate_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='投资经验标签'),
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', '公开'), ('FOLLOWERS', '仅关注者可见'), ('PRIVATE', '仅自己可见')], default='PUBLIC', max_length=16, verbose_name='主页可见性')),
                ('show_invest_profile', models.BooleanField(default=True, verbose_name='展示投资偏好')),
                ('allow_search', models.BooleanField(default=True, verbose_name='允许被搜索')),
                ('show_email', models.BooleanField(default=False, verbose_name='展示邮箱')),
                ('show_phone', models.BooleanField(default=False, verbose_name='展示手机号')),
                ('allow_stranger_dm', models.BooleanField(default=True, verbose_name='允许陌生人私信')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户隐私设置',
                'verbose_name_plural': '用户隐私设置',
                'db_table': 'user_privacy_settings',
            },
        ),
    ]
