# Generated by Django 5.1.4 on 2026-03-27 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_investment_experience_userprivacysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('POST_PUBLISHED', '发布帖子'), ('PORTFOLIO_PUBLISHED', '发布组合'), ('GROUP_POST_PUBLISHED', '发布群讨论')], max_length=40, verbose_name='动作类型')),
                ('object_type', models.CharField(choices=[('POST', '帖子'), ('PORTFOLIO', '组合'), ('GROUP_POST', '群讨论')], max_length=20, verbose_name='对象类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='排序分值')),
                ('is_star_actor', models.BooleanField(default=False, verbose_name='是否特别关注用户')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_feed_actor_items', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_feed_items', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '关注动态项',
                'verbose_name_plural': '关注动态项',
                'db_table': 'follow_feed_item',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_feed_user_time'), models.Index(fields=['user', 'is_star_actor', '-created_at'], name='idx_feed_user_star_time'), models.Index(fields=['object_type', 'object_id'], name='idx_feed_object')],
                'unique_together': {('user', 'action_type', 'object_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserStarFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_followers_set', to=settings.AUTH_USER_MODEL, verbose_name='被星标用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_following_set', to=settings.AUTH_USER_MODEL, verbose_name='星标用户')),
            ],
            options={
                'verbose_name': '用户特别关注',
                'verbose_name_plural': '用户特别关注',
                'db_table': 'user_star_follow',
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_star_f_user_id_c1907c_idx'), models.Index(fields=['follow_user'], name='user_star_f_follow__88ff32_idx')],
                'unique_together': {('user', 'follow_user')},
            },
        ),
    ]
