# Generated by Django 5.1.4 on 2026-03-27 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_followfeeditem_userstarfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='内容质量分'),
        ),
        migrations.AlterField(
            model_name='usermoderationlog',
            name='action',
            field=models.CharField(choices=[('WARNING', '警告'), ('MUTE', '禁言'), ('UNMUTE', '解除禁言'), ('BAN', '封禁'), ('UNBAN', '解除封禁'), ('RATE_LIMIT', '限流'), ('STATUS_CHANGE', '状态变更')], max_length=32, verbose_name='动作类型'),
        ),
        migrations.CreateModel(
            name='LevelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='等级')),
                ('min_points', models.IntegerField(verbose_name='最低积分')),
                ('max_points', models.IntegerField(verbose_name='最高积分')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='等级称号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '等级规则',
                'verbose_name_plural': '等级规则',
                'db_table': 'level_rule',
                'ordering': ['level'],
                'indexes': [models.Index(fields=['is_active', 'level'], name='idx_level_rule_active_level')],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='发帖数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('reported_count', models.PositiveIntegerField(default=0, verbose_name='被举报数')),
                ('violation_count', models.PositiveIntegerField(default=0, verbose_name='违规数')),
                ('received_likes', models.PositiveIntegerField(default=0, verbose_name='获赞数')),
                ('taken_down_count', models.PositiveIntegerField(default=0, verbose_name='下架数')),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='质量分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_daily', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为日统计',
                'verbose_name_plural': '用户行为日统计',
                'db_table': 'user_behavior_daily',
                'indexes': [models.Index(fields=['stat_date'], name='idx_ubehavior_date'), models.Index(fields=['user', 'stat_date'], name='idx_ubehavior_user_date')],
                'unique_together': {('user', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='UserPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='积分变动值')),
                ('event_type', models.CharField(choices=[('POST_CREATED', '发帖'), ('COMMENT_CREATED', '评论'), ('CONTENT_LIKED', '内容获赞'), ('CONTENT_REJECTED', '内容驳回'), ('MODERATION_PENALTY', '治理处罚扣分'), ('ADMIN_ADJUST', '管理员调整')], max_length=32, verbose_name='事件类型')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源类型')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='变动原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_point_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户积分流水',
                'verbose_name_plural': '用户积分流水',
                'db_table': 'user_point_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_upoint_user_time'), models.Index(fields=['event_type', '-created_at'], name='idx_upoint_event_time')],
            },
        ),
    ]
