# Generated by Django 4.2.7 on 2026-01-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CONTENT_RISK', '内容风险'), ('USER_BEHAVIOR', '用户行为'), ('SYSTEM', '系统异常')], max_length=50, verbose_name='告警类型')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('description', models.TextField(verbose_name='告警描述')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('severity', models.CharField(default='MEDIUM', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('OPEN', '待处理'), ('RESOLVED', '已处理'), ('IGNORED', '已忽略')], default='OPEN', max_length=20, verbose_name='处理状态')),
                ('handle_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_handled', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '风控告警',
                'verbose_name_plural': '风控告警',
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('POST', '帖子'), ('COMMENT', '评论'), ('USER', '用户')], max_length=20, verbose_name='举报目标类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='举报目标ID')),
                ('reason', models.TextField(verbose_name='举报原因')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RESOLVED', '已处理')], default='PENDING', max_length=20, verbose_name='处理状态')),
                ('handle_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='举报时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_9e629c_idx'), models.Index(fields=['target_type', 'target_id'], name='report_target__0f58e8_idx')],
            },
        ),
    ]
