# Generated by Django 5.1.4 on 2026-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='证据内容（截图、链接等）'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='举报类型细分'),
        ),
        migrations.AddField(
            model_name='report',
            name='result',
            field=models.CharField(blank=True, max_length=20, verbose_name='处理结果类型'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('POST', '帖子'), ('COMMENT', '评论'), ('USER', '用户'), ('PORTFOLIO', '组合')], max_length=20, verbose_name='举报目标类型'),
        ),
    ]
