# Generated by Django 5.1.4 on 2026-03-27 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_moderation_source_content_risk_level_and_more'),
        ('reports', '0002_report_evidence_json_report_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(unique=True, verbose_name='统计日期')),
                ('dau', models.PositiveIntegerField(default=0, verbose_name='日活')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='发帖数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('report_count', models.PositiveIntegerField(default=0, verbose_name='举报数')),
                ('review_pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='审核通过率')),
                ('taken_down_count', models.PositiveIntegerField(default=0, verbose_name='下架数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社区日指标',
                'verbose_name_plural': '社区日指标',
                'db_table': 'community_metric_daily',
                'ordering': ['-stat_date'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(blank=True, max_length=32, verbose_name='处置动作'),
        ),
        migrations.CreateModel(
            name='ModerationQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('AUTO', '自动规则'), ('REPORT', '举报触发'), ('MANUAL', '人工添加')], default='AUTO', max_length=16, verbose_name='来源')),
                ('risk_level', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], default='LOW', max_length=16, verbose_name='风险等级')),
                ('risk_score', models.PositiveIntegerField(default=0, verbose_name='风险分')),
                ('reason_summary', models.CharField(blank=True, max_length=255, verbose_name='原因摘要')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RESOLVED', '已处理')], default='PENDING', max_length=16, verbose_name='状态')),
                ('decided_status', models.CharField(blank=True, max_length=20, verbose_name='最终状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue_items', to='content.content', verbose_name='内容')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_moderation_queue_items', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '审核队列项',
                'verbose_name_plural': '审核队列项',
                'db_table': 'moderation_queue_item',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='linked_queue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_reports', to='reports.moderationqueueitem', verbose_name='关联审核队列项'),
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('SENSITIVE_WORD', '敏感词'), ('COMPLIANCE_POLICY', '合规规则'), ('REPETITION', '重复检测')], max_length=32, verbose_name='规则类型')),
                ('pattern', models.CharField(blank=True, max_length=255, verbose_name='匹配模式')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='规则配置')),
                ('risk_level', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], default='LOW', max_length=16, verbose_name='风险等级')),
                ('risk_score', models.PositiveIntegerField(default=10, verbose_name='风险分')),
                ('action', models.CharField(choices=[('ALLOW', '放行'), ('REVIEW', '转人工审核'), ('REJECT', '自动驳回')], default='REVIEW', max_length=16, verbose_name='命中动作')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核规则',
                'verbose_name_plural': '审核规则',
                'db_table': 'moderation_rule',
                'ordering': ['rule_type', 'id'],
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='idx_mrule_active_type')],
            },
        ),
        migrations.CreateModel(
            name='ModerationHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_text', models.CharField(blank=True, max_length=255, verbose_name='命中文本')),
                ('evidence_json', models.JSONField(blank=True, default=dict, verbose_name='命中证据')),
                ('risk_score', models.PositiveIntegerField(default=0, verbose_name='风险分')),
                ('risk_level', models.CharField(default='LOW', max_length=16, verbose_name='风险等级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_hits', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_hits', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='reports.moderationrule')),
            ],
            options={
                'verbose_name': '审核命中记录',
                'verbose_name_plural': '审核命中记录',
                'db_table': 'moderation_hit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('topic', models.CharField(max_length=64, verbose_name='话题')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='帖子数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('heat_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='热度分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话题日指标',
                'verbose_name_plural': '话题日指标',
                'db_table': 'topic_metric_daily',
                'ordering': ['-stat_date', '-heat_score'],
                'indexes': [models.Index(fields=['stat_date', '-heat_score'], name='idx_tmetric_date_heat'), models.Index(fields=['topic', '-stat_date'], name='idx_tmetric_topic_date')],
                'unique_together': {('stat_date', 'topic')},
            },
        ),
        migrations.AddIndex(
            model_name='moderationqueueitem',
            index=models.Index(fields=['status', '-created_at'], name='idx_mqueue_status_time'),
        ),
        migrations.AddIndex(
            model_name='moderationqueueitem',
            index=models.Index(fields=['source', 'status'], name='idx_mqueue_source_status'),
        ),
        migrations.AddIndex(
            model_name='moderationqueueitem',
            index=models.Index(fields=['risk_level', '-risk_score'], name='idx_mqueue_risk_score'),
        ),
        migrations.AddIndex(
            model_name='moderationhit',
            index=models.Index(fields=['content', '-created_at'], name='idx_mhit_content_time'),
        ),
        migrations.AddIndex(
            model_name='moderationhit',
            index=models.Index(fields=['user', '-created_at'], name='idx_mhit_user_time'),
        ),
    ]
