# Generated by Django 5.1.4 on 2026-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', '点赞通知'), ('COMMENT', '评论通知'), ('FOLLOW', '关注通知'), ('REVIEW_RESULT', '审核结果通知'), ('MENTION', '@提及通知'), ('POLL_VOTED', '投票通知'), ('ATTACHMENT_REVIEWED', '附件审核通知'), ('SYSTEM', '系统通知')], max_length=20, verbose_name='通知类型'),
        ),
    ]
