"""
Django settings for invest_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# ── 自动加载 .env 文件到系统环境变量（override=True：.env 优先于 shell 设置）──
# 使用 python-dotenv；若未安装则 fallback 到手动解析
# 这样 os.environ.get('FINNHUB_API_KEY') 在任何地方都能正确读取
_BASE_DIR_EARLY = Path(__file__).resolve().parent.parent
_env_file = _BASE_DIR_EARLY / '.env'

try:
    from dotenv import load_dotenv as _load_dotenv
    if _env_file.exists():
        _load_dotenv(str(_env_file), override=True)  # override=True: .env 覆盖已有 shell 变量
except ImportError:
    # fallback：手动解析 .env（覆盖模式）
    if _env_file.exists():
        with open(_env_file, encoding='utf-8') as _f:
            for _line in _f:
                _line = _line.strip()
                if _line and not _line.startswith('#') and '=' in _line:
                    _k, _v = _line.split('=', 1)
                    os.environ[_k.strip()] = _v.strip()  # 直接覆盖

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 优先从环境变量读取，未配置时退回开发默认值
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-your-secret-key-here-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# 本地开发默认 True，生产环境请设置 DJANGO_DEBUG=false
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

# 生产环境请显式配置 DJANGO_ALLOWED_HOSTS（以逗号分隔）
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]

# 关闭Django的自动添加斜杠功能，避免POST请求重定向问题
APPEND_SLASH = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Local apps
    'accounts',
    'content',
    'portfolios',
    'notifications',
    'reports',
    'market_data',  # 行情数据模块（Finnhub 接入）
    'messages',     # 私信与会话模块
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invest_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invest_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'community_db',  # 修改为您创建的数据库名
        'USER': 'root',
        'PASSWORD': '123456',  # 请修改为您的MySQL密码
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# OAuth providers (微信/微博)
WECHAT_APP_ID = os.environ.get('WECHAT_APP_ID', '')
WECHAT_APP_SECRET = os.environ.get('WECHAT_APP_SECRET', '')
WECHAT_REDIRECT_URI = os.environ.get('WECHAT_REDIRECT_URI', '')

WEIBO_CLIENT_ID = os.environ.get('WEIBO_CLIENT_ID', '')
WEIBO_CLIENT_SECRET = os.environ.get('WEIBO_CLIENT_SECRET', '')
WEIBO_REDIRECT_URI = os.environ.get('WEIBO_REDIRECT_URI', '')

# CORS settings for frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

# Email (QQ SMTP / other providers)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'false').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'true').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_FROM = os.environ.get('EMAIL_FROM', DEFAULT_FROM_EMAIL)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))

# SMS provider
# SMS_PROVIDER=MOCK | TWILIO | HTTP
SMS_PROVIDER = os.environ.get('SMS_PROVIDER', 'MOCK')

# Twilio settings (SMS_PROVIDER=TWILIO)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_PHONE = os.environ.get('TWILIO_FROM_PHONE', '')

# Generic HTTP SMS gateway settings (SMS_PROVIDER=HTTP)
SMS_HTTP_URL = os.environ.get('SMS_HTTP_URL', '')
SMS_HTTP_TOKEN = os.environ.get('SMS_HTTP_TOKEN', '')

# ─────────────────────────────────────────────────────────────────────────────
# Finnhub 行情数据接入配置（美股 / 港股）
# 规范（finnhub-api.mdc §1）：
#   - Key 从环境变量 FINNHUB_API_KEY 读取，禁止明文写入代码或日志
#   - 此处不打印 Key 值，只存在布尔状态检查
# 配置方式（二选一）：
#   1. 项目根目录新建 .env 文件（不入库）：FINNHUB_API_KEY=your_key_here
#   2. 系统环境变量：set FINNHUB_API_KEY=your_key_here (Windows)
# ─────────────────────────────────────────────────────────────────────────────
FINNHUB_API_KEY_CONFIGURED = bool(os.environ.get('FINNHUB_API_KEY', ''))

# 行情快照缓存时间（秒）：quote 接口的有效期
# 同时作为 Django Cache（L1）与 DB 快照（L2）的 TTL
# 建议：交易时段设 30~60，非交易时段可放大至 300
FINNHUB_QUOTE_CACHE_TTL = int(os.environ.get('FINNHUB_QUOTE_CACHE_TTL', 60))

# K 线数据保留天数（超出此日期的快照将被定期清理）
MARKET_DATA_SNAPSHOT_RETENTION_DAYS = int(os.environ.get('MARKET_DATA_SNAPSHOT_RETENTION_DAYS', 7))

# 热门标的定时刷新：quote_refresh_popular 每次刷新的标的数量上限
# 对应 get_popular_asset_ids(top_n) 的默认值
# 建议：免费版 Finnhub Key 速率限制 60 次/分，TOP_N 不超过 30
QUOTE_REFRESH_POPULAR_TOP_N = int(os.environ.get('QUOTE_REFRESH_POPULAR_TOP_N', 20))

# ─────────────────────────────────────────────────────────────────────────────
# Tushare 行情数据接入配置（A 股：沪深京三市）
# 规范：
#   - Token 从环境变量 TUSHARE_API_TOKEN 读取，禁止明文写入代码或日志
#   - 数据源路由：market in {SH,SZ,BJ} → Tushare；US/HK → Finnhub
# 配置方式（.env 文件，与 Finnhub Key 同文件）：
#   TUSHARE_API_TOKEN=your_token_here
# ─────────────────────────────────────────────────────────────────────────────
TUSHARE_API_TOKEN_CONFIGURED = bool(os.environ.get('TUSHARE_API_TOKEN', ''))

# A 股行情快照 TTL（秒）
# A 股只有日线收盘数据，建议设置较长 TTL（收盘后数据不再变化）
# 交易时段建议 300s，收盘后可放大至 3600
TUSHARE_QUOTE_CACHE_TTL = int(os.environ.get('TUSHARE_QUOTE_CACHE_TTL', 300))

# A 股每次同步时 Tushare 请求间隔（秒），防止触发 API 限流
# Tushare 免费版限制每分钟约 500 次，但建议保守设置
TUSHARE_REQUEST_DELAY = float(os.environ.get('TUSHARE_REQUEST_DELAY', 0.4))

# ─────────────────────────────────────────────────────────────────────────────
# 缓存配置（行情快照优先读 Redis，降低数据库压力）
# 若未安装 Redis，自动降级为本地内存缓存（LocMemCache）
# ─────────────────────────────────────────────────────────────────────────────
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')

if os.environ.get('USE_REDIS', 'false').lower() == 'true':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'IGNORE_EXCEPTIONS': True,  # Redis 不可用时降级到内存缓存
            },
            'KEY_PREFIX': 'invest_market',
            'TIMEOUT': 60,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'invest-market-cache',
        }
    }

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}