# Generated by Django 5.1.4 on 2026-03-27 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群组名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='唯一标识')),
                ('description', models.TextField(blank=True, verbose_name='群简介')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像链接')),
                ('tags_json', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('topic_direction', models.CharField(blank=True, max_length=120, verbose_name='主题方向')),
                ('visibility', models.CharField(choices=[('PUBLIC', '公开'), ('PRIVATE', '私密'), ('APPROVAL', '审核加入')], default='PUBLIC', max_length=20, verbose_name='可见性')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('DISSOLVED', '已解散')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('member_count', models.PositiveIntegerField(default=1, verbose_name='成员数')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='讨论数')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='资料数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
            ],
            options={
                'verbose_name': '群组',
                'verbose_name_plural': '群组',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='group_files/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('visibility', models.CharField(choices=[('GROUP_ONLY', '仅群内')], default='GROUP_ONLY', max_length=20, verbose_name='可见性')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DELETED', '已删除')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.group', verbose_name='群组')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '群资料',
                'verbose_name_plural': '群资料',
                'db_table': 'group_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='申请说明')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group', verbose_name='群组')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '入群申请',
                'verbose_name_plural': '入群申请',
                'db_table': 'group_join_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', '群主'), ('ADMIN', '管理员'), ('MEMBER', '普通成员')], default='MEMBER', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('ACTIVE', '在群'), ('LEFT', '已退出'), ('REMOVED', '被移除')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group', verbose_name='群组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '群成员',
                'verbose_name_plural': '群成员',
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('content_type', models.CharField(choices=[('NORMAL', '普通讨论'), ('LONGFORM', '长文分析'), ('POLL', '投票')], default='NORMAL', max_length=20, verbose_name='内容类型')),
                ('status', models.CharField(choices=[('PUBLISHED', '已发布'), ('DELETED', '已删除')], default='PUBLISHED', max_length=20, verbose_name='状态')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group', verbose_name='群组')),
            ],
            options={
                'verbose_name': '群讨论',
                'verbose_name_plural': '群讨论',
                'db_table': 'group_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='groups_visibil_6d42d6_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner', '-created_at'], name='groups_owner_i_cfd0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='groupfile',
            index=models.Index(fields=['group', '-created_at'], name='group_files_group_i_c606d6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupfile',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='group_files_uploade_d0c623_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status', '-created_at'], name='group_join__group_i_9b4a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', '-created_at'], name='group_join__user_id_92a940_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role', 'status'], name='group_membe_group_i_d3bcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user', 'status'], name='group_membe_user_id_942afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='grouppost',
            index=models.Index(fields=['group', 'status', '-created_at'], name='group_posts_group_i_7a6420_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppost',
            index=models.Index(fields=['author', '-created_at'], name='group_posts_author__421a9a_idx'),
        ),
    ]
