# Generated by Django 5.1.4 on 2026-03-27 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_owner_as_reviewer(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    GroupReviewer = apps.get_model('groups', 'GroupReviewer')
    rows = []
    for group in Group.objects.filter(status='ACTIVE', visibility='APPROVAL').only('id', 'owner_id'):
        rows.append(GroupReviewer(group_id=group.id, user_id=group.owner_id))
    if rows:
        GroupReviewer.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='邀请说明')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='groups.group', verbose_name='群组')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invites', to=settings.AUTH_USER_MODEL, verbose_name='被邀请人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '群邀请',
                'verbose_name_plural': '群邀请',
                'db_table': 'group_invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'status', '-created_at'], name='group_invit_group_i_732961_idx'), models.Index(fields=['invitee', 'status', '-created_at'], name='group_invit_invitee_188795_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='groups.group', verbose_name='群组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_reviewer_roles', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '群审核人',
                'verbose_name_plural': '群审核人',
                'db_table': 'group_reviewers',
                'indexes': [models.Index(fields=['group', 'created_at'], name='group_revie_group_i_d9b1cf_idx'), models.Index(fields=['user', 'created_at'], name='group_revie_user_id_427be1_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.RunPython(seed_owner_as_reviewer, migrations.RunPython.noop),
    ]
