# Generated by Django 4.2.7 on 2026-01-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='组合名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('risk_level', models.CharField(choices=[('Low', '低风险'), ('Medium', '中风险'), ('High', '高风险')], default='Medium', max_length=20, verbose_name='风险等级')),
                ('returns_ytd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='年初至今回报')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '投资组合',
                'verbose_name_plural': '投资组合',
                'db_table': 'portfolio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='资产代码')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='仓位百分比')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolio', verbose_name='所属组合')),
            ],
            options={
                'verbose_name': '组合资产',
                'verbose_name_plural': '组合资产',
                'db_table': 'portfolio_asset',
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['owner', '-created_at'], name='portfolio_owner_i_61896c_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_public', '-returns_ytd'], name='portfolio_is_publ_73e707_idx'),
        ),
    ]
