# Generated by Django 5.1.4 on 2026-02-26 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_asset_fk_and_user_holding'),
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='持有股数/份额', max_digits=18, verbose_name='持有数量')),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, help_text='买入均价（元/股）', max_digits=12, verbose_name='成本均价')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人持仓',
                'verbose_name_plural': '个人持仓',
                'db_table': 'user_holding',
            },
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='指向 content_asset 表的真实资产记录', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assets', to='content.asset', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, verbose_name='资产代码'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together={('portfolio', 'asset')},
        ),
        migrations.AddIndex(
            model_name='portfolioasset',
            index=models.Index(fields=['portfolio', 'asset'], name='portfolio_a_portfol_c678fa_idx'),
        ),
        migrations.AddField(
            model_name='userholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_holdings', to='content.asset', verbose_name='持有资产'),
        ),
        migrations.AddField(
            model_name='userholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL, verbose_name='持有人'),
        ),
        migrations.AddIndex(
            model_name='userholding',
            index=models.Index(fields=['user', 'asset'], name='user_holdin_user_id_834ed8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userholding',
            unique_together={('user', 'asset')},
        ),
    ]
