# Generated by Django 5.1.4 on 2026-02-26 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_asset_fk_and_user_holding'),
        ('portfolios', '0003_holding_daily_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userholding',
            index=models.Index(fields=['asset'], name='idx_holding_asset'),
        ),
    ]
