# Generated by Django 5.1.4 on 2026-03-15 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_add_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论作者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portfolios.portfoliocomment', verbose_name='父评论')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolios.portfolio', verbose_name='所属组合')),
                ('reply_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='被回复用户')),
            ],
            options={
                'verbose_name': '组合评论',
                'verbose_name_plural': '组合评论',
                'db_table': 'portfolio_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='更新标题')),
                ('content', models.TextField(verbose_name='更新内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='portfolios.portfolio', verbose_name='组合')),
            ],
            options={
                'verbose_name': '组合更新日志',
                'verbose_name_plural': '组合更新日志',
                'db_table': 'portfolio_update_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订阅时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='portfolios.portfolio', verbose_name='组合')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '组合订阅',
                'verbose_name_plural': '组合订阅',
                'db_table': 'portfolio_subscription',
                'unique_together': {('portfolio', 'user')},
            },
        ),
    ]
