# Generated by Django 5.1.4 on 2026-03-27 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_portfoliocomment_portfolioupdatelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='strategy_note',
            field=models.TextField(blank=True, verbose_name='策略说明'),
        ),
        migrations.CreateModel(
            name='PortfolioFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='portfolios.portfolio', verbose_name='组合')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '组合收藏',
                'verbose_name_plural': '组合收藏',
                'db_table': 'portfolio_favorite',
                'indexes': [models.Index(fields=['portfolio', 'created_at'], name='idx_portfolio_fav_portfolio'), models.Index(fields=['user', 'created_at'], name='idx_portfolio_fav_user')],
                'unique_together': {('portfolio', 'user')},
            },
        ),
    ]
