# Generated by Django 5.1.4 on 2026-04-06 06:14

from django.conf import settings
from django.db import migrations, models


def _backfill_subscription_count(apps, schema_editor):
    Portfolio = apps.get_model('portfolios', 'Portfolio')
    Sub = apps.get_model('portfolios', 'PortfolioSubscription')
    from django.db.models import Count

    agg = Sub.objects.values('portfolio_id').annotate(c=Count('id'))
    for row in agg.iterator(chunk_size=500):
        Portfolio.objects.filter(pk=row['portfolio_id']).update(subscription_count=row['c'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfolio_strategy_note_portfoliofavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subscription_count',
            field=models.PositiveIntegerField(default=0, verbose_name='订阅数'),
        ),
        migrations.AddIndex(
            model_name='portfoliocomment',
            index=models.Index(fields=['portfolio', 'created_at'], name='idx_portfolio_cmt_port_time'),
        ),
        migrations.AddIndex(
            model_name='portfoliocomment',
            index=models.Index(fields=['parent', 'created_at'], name='idx_portfolio_cmt_parent_time'),
        ),
        migrations.AddIndex(
            model_name='portfoliosubscription',
            index=models.Index(fields=['user', '-created_at'], name='idx_portfolio_sub_user_time'),
        ),
        migrations.AddIndex(
            model_name='portfoliosubscription',
            index=models.Index(fields=['portfolio', '-created_at'], name='idx_portfolio_sub_port_time'),
        ),
        migrations.RunPython(_backfill_subscription_count, migrations.RunPython.noop),
    ]
